# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-14 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0003_auto_20170914_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banheiro',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='imagens/banheiros'),
        ),
        migrations.AlterField(
            model_name='cozinha',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='imagens/cozinha'),
        ),
        migrations.AlterField(
            model_name='quarto',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='imagens/quarto'),
        ),
        migrations.AlterField(
            model_name='sala',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='imagens/sala'),
        ),
    ]
