# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-14 18:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0005_estilo'),
    ]

    operations = [
        migrations.AddField(
            model_name='banheiro',
            name='estilo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='perfil.Estilo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cozinha',
            name='estilo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='perfil.Estilo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quarto',
            name='estilo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='perfil.Estilo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sala',
            name='estilo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='perfil.Estilo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='banheiro',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='imagens/banheiro'),
        ),
    ]
