# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-14 18:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0006_auto_20170914_1542'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banheiro',
            old_name='foto',
            new_name='imagem',
        ),
        migrations.RenameField(
            model_name='cozinha',
            old_name='foto',
            new_name='imagem',
        ),
        migrations.RenameField(
            model_name='quarto',
            old_name='foto',
            new_name='imagem',
        ),
        migrations.RenameField(
            model_name='sala',
            old_name='foto',
            new_name='imagem',
        ),
    ]
